name: DjA
favicon: null
layout_spectrum: 0.83545
typography_spectrum: 0.8592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#151515'
    - '#cacaca'
    - '#8f8f8f'
    - '#6e6e6e'
  brandStrength: 0.44659954449161887
  lightness: 0.3660637238062918
  saturation: 0.15491947205737233
  rhythmicContrast: 0.078011907171458
purpose: []
